# Generated by Django 5.2.7 on 2025-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='urlsFilm',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen'),
        ),
    ]
