# Generated by Django 5.2.7 on 2025-11-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaAPP', '0002_actividad_urlsfilm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='urlsFilm',
            new_name='fotoActividad',
        ),
        migrations.AddField(
            model_name='viaje',
            name='fotoViaje',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen'),
        ),
    ]
