# Generated by Django 5.2.7 on 2025-12-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaAPP', '0003_rename_urlsfilm_actividad_fotoactividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('personas', models.PositiveIntegerField(default=1)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='AgenciaAPP.viaje')),
            ],
        ),
    ]
