# Generated by Django 5.2.7 on 2025-12-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaAPP', '0004_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
