# Generated by Django 5.2.7 on 2025-12-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaAPP', '0005_alter_actividad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='hotel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
